import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { Inter, Lora } from "next/font/google";
import { cx } from "@/utils/all";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter"
});

const lora = Lora({
  subsets: ["latin"],
  variable: "--font-lora"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html  suppressHydrationWarning lang="en">
      <body className={cx(inter.variable, lora.variable)}>
        <Providers>
          {children}
        </Providers>
        </body>
    </html>
  );
}
export const revalidate = 60;
